[build]
target = "xtensa-esp32-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"
runner = "espflash flash --baud 460800 --monitor"
rustflags = [ "--cfg",  "espidf_time64"] # Extending time_t for ESP IDF 5: https://github.com/esp-rs/rust/issues/110

[unstable]
build-std = ["core", "alloc", "panic_abort"]

[env]
# ESP_IDF_VERSION = "v5.1"
IDF_PATH = "vendor/esp-idf"
